const tintColor = '#ec7e23';

export default {
  tintColor,
  tabIconDefault: '#ccc',
  tabIconSelected: tintColor,
  tabBar: '#fefefe',
  errorBackground: 'red',
  errorText: '#fff',
  white: '#FFF',
  warningBackground: '#EAEB5E',
  warningText: '#666804',
  noticeBackground: tintColor,
  noticeText: '#fff',
  pageTitle: '#464646',
  inputBorder: '#d0d0d0',
  caribbeanGreen: '#3bb773',
  purple: '#9E7BFF',
  violet: '#852b99',
  ferrariRed: '#FF2800',
  bitterSweetRed: '#ff6961',
  salmonRed: '#FA8072',
  electricBlue: '#7EF9FF',
  bluishGreen: '#0D98BA',
  bumblebeeYellow: '#FCE205',
  lemonYellow: '#EFFD5F',
  peachYellow: '#FFE5B4',
  cottonPink: '#FFB3DE',
  mauvePink: '#EFC0FE',
  webOrange: '#FFA600',
  anaklawaBlue: '#A2CFFE'
};
